// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbops

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ApiKey struct {
	ID        int64        `json:"id"`
	Key       string       `json:"key"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Event struct {
	ID        int64        `json:"id"`
	Edition   int32        `json:"edition"`
	GameType  string       `json:"game_type"`
	StartsAt  sql.NullTime `json:"starts_at"`
	EndsAt    sql.NullTime `json:"ends_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type EventFinish struct {
	ID             int64        `json:"id"`
	MapID          int64        `json:"map_id"`
	PlayerID       int64        `json:"player_id"`
	Score          int32        `json:"score"`
	FinishCounter  int32        `json:"finish_counter"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	LastFinishedAt sql.NullTime `json:"last_finished_at"`
}

type Finish struct {
	ID             int64        `json:"id"`
	MapID          int64        `json:"map_id"`
	PlayerID       int64        `json:"player_id"`
	Score          int32        `json:"score"`
	FinishCounter  int32        `json:"finish_counter"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	LastFinishedAt sql.NullTime `json:"last_finished_at"`
}

type KarmaVote struct {
	ID        int64        `json:"id"`
	MapID     int64        `json:"map_id"`
	PlayerID  int64        `json:"player_id"`
	Vote      float64      `json:"vote"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Map struct {
	ID            int64        `json:"id"`
	Uuid          string       `json:"uuid"`
	EventID       int64        `json:"event_id"`
	FullName      string       `json:"full_name"`
	Number        int32        `json:"number"`
	Author        string       `json:"author"`
	AuthorTime    int32        `json:"author_time"`
	TotalFinishes int32        `json:"total_finishes"`
	TotalPlaytime int32        `json:"total_playtime"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type PlayerEditionStat struct {
	ID       int64   `json:"id"`
	PlayerID int64   `json:"player_id"`
	Average  float64 `json:"average"`
	Finishes int32   `json:"finishes"`
	EventID  int64   `json:"event_id"`
}

type Server struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	GameType   string        `json:"game_type"`
	Difficulty sql.NullInt32 `json:"difficulty"`
	Timelimit  int32         `json:"timelimit"`
	Online     int8          `json:"online"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type TmPlayer struct {
	ID            int64          `json:"id"`
	Login         string         `json:"login"`
	AccountID     sql.NullString `json:"account_id"`
	GameType      sql.NullString `json:"game_type"`
	Zone          sql.NullString `json:"zone"`
	TotalFinishes int32          `json:"total_finishes"`
	Nickname      sql.NullString `json:"nickname"`
	Role          sql.NullString `json:"role"`
	IsMuted       sql.NullInt16  `json:"is_muted"`
	IsBlacklisted sql.NullInt16  `json:"is_blacklisted"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type UserMetadatum struct {
	ID           int64           `json:"id"`
	UserID       int64           `json:"user_id"`
	StreamData   json.RawMessage `json:"stream_data"`
	Tags         json.RawMessage `json:"tags"`
	Difficulties json.RawMessage `json:"difficulties"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type WebUser struct {
	ID           int64          `json:"id"`
	DiscordLogin string         `json:"discord_login"`
	Tm20PlayerID sql.NullInt64  `json:"tm20_player_id"`
	TmnfPlayerID sql.NullInt64  `json:"tmnf_player_id"`
	Role         sql.NullString `json:"role"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type WorldRecord struct {
	ID        int64        `json:"id"`
	MapID     int64        `json:"map_id"`
	WrHolder  string       `json:"wr_holder"`
	Score     int32        `json:"score"`
	Source    string       `json:"source"`
	DrivenAt  time.Time    `json:"driven_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
