services:
  kacky_gsb:
    container_name: kackyGSB
    restart: unless-stopped
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - UNAME=${UNAME:-devUser}
        - MARIADBVER=${MYSQL_VER:-11.4.2}
    tty: true
    env_file: ".env.dev"
    volumes:
      - ..:/go/src/kacky-gameserver-backend:cached
    depends_on:
      kacky_db:
        condition: service_healthy
      kacky_nats:
        condition: service_started

  kacky_nats:
    image: nats:${NATS_VER:-2.10-alpine}
    container_name: kackyNATS
    restart: unless-stopped
    volumes:
      - ./nats-dev-server.conf:/etc/nats/nats-server.conf:ro
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    depends_on:
      kacky_db:
        condition: service_healthy

  kacky_db:
    image: mariadb:${MYSQL_VER:-11.4.2}
    container_name: kackyDB
    restart: unless-stopped
    env_file: ".env.dev"
    volumes:
      - ${PWD}/.devcontainer/db-mock-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: kacky-development-network
